### ISSUE TITLE
Field to upload images

### ISSUE THREAD

**Issue by luizbills** [luizbills/better-wordpress-admin-api#4]

**Comment by Basilakis** [comment]
Any update on that? :)

**Comment by luizbills** [comment]
Not yet. I'm out of time. Feel free to help with a PR :smiley:

**Comment by luizbills** [comment]
renamed this issue to __Field to upload images__ from *Field to upload files*

**Comment by luizbills** [comment]
Field implemented.
https://github.com/luizbills/better-wordpress-admin-api/blob/master/docs/field-types.md#image
