### ISSUE TITLE
Accessing field values

### ISSUE THREAD

**Issue by dsentker** [luizbills/better-wordpress-admin-api#5]
I put the code to create admin inputs on my functions.php. The fields are displayed properly in backend. When i try to access the method get_field_value() in header.php, i got the excception 

> Trying to get value of an undefined field with id: 'f_phone'

. I debugged the _WP_Admin_Page instance and saw that the $fields array in the _WP_Admin_Page is empty. It seems that the values are filled AFTER i want to access them. How can i avoid that?

**Comment by luizbills** [comment]
I can see that.
You can't avoid :cry:  this was a mistake mine
I'm working in a fix.
Thanks for testing.

**Comment by luizbills** [comment]
@dsentker fixed. Update your files please.

You do'nt need use `$your_page->on_setup` anymore (this function was removed).
Now it's simpler:
```php
// create your page
$your_page = wp_create_admin_page( /* page args */ );

// add your fields
$your_page->add_field( /* field args */ );
```

And you can access/get the values with:
```php
$value = $your_page->get_field_value( $field_id );
// or
$value = wp_get_page_field_value( $page_id, $field_id );
```

Also, you can retrieve/get a page (`_WP_Admin_Page`) instance:
```php
$your_page = wp_get_admin_page( $page_id, $field_id );
```

Thanks again, man

**Comment by luizbills** [comment]
Let me know if you are finding more issues

**Comment by dsentker** [comment]
Thanks for the quick fix. I can test it in a few days.

**Comment by luizbills** [comment]
I'll close this issue, but please reopen if necessary
